enyo.depends(
  "$lib/onyx",
  "$lib/layout",
  "$lib/jquery/jquery-1.8.2.min.js",
  "$lib/tools",
  "$lib/backbone-x/lib/backbone/backbone.js",
  "$lib/enyo-x/source/views/screen_carousel.js",
  "$lib/enyo-x/source/views/list.js",
  "stylesheets/screen.css",
  "core.js",
  "views",
  "app.js",
  "router.js",
  "models"
);
