enyo.depends(
  "$lib/onyx",
  "$lib/layout",
  "$lib/client/lib/underscore",
  "$lib/client/lib/jquery",
  "$lib/client/lib/backbone",
  "$lib/client/source/core.js",
  "$lib/client/source/xt",
  "$lib/client/source/xv/views/screen_carousel.js",
  "$lib/client/source/xv/views/list.js",
  "stylesheets/screen.css",
  "core.js",
  "views",
  "app.js",
  "router.js",
  "models"
);